---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dfuseplugin
  labels:
      name: pv-dfuseplugin
spec:
  capacity:
    storage: 10Gi # dummy
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: dfuse.csi.k8s.io
    volumeHandle: unique-volid  # make sure it's a unique id in the cluster
    volumeAttributes:
      uid: "0"
      size: "8G"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dfuseplugin
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["pv-dfuseplugin"]
---
kind: Pod
apiVersion: v1
metadata:
  name: test-app
spec:
  containers:
    - name: test
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: dfuse
      command: [ "sleep", "1000000" ]
  volumes:
    - name: dfuse
      csi:
        driver: dfuse.csi.k8s.io
