---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dfuse-csi
provisioner: dfuse.csi.k8s.io
parameters:
  server: 192.168.122.1
  share: /
reclaimPolicy: Delete
volumeBindingMode: Immediate
#mountOptions:
#  - hard
#  - nfsvers=4.1
